themes/pzq: Add pzq themes inspired by ys-theme from oh-my-zsh and rana
ohmybash/oh-my-bash pull request #250
Opened 2021-10-22 13:25 UTC by ZQPei

* Add pzq theme, which is inspired on ys-theme from oh-my-zsh and rana theme
* The pzq theme solves the problem of misplaced commands in rena

2021-12-24 11:36 UTC, akinomyoga requested changes

2021-12-24 11:36 UTC, akinomyoga commented on themes/pzq/pzq.theme.sh
> +  code=$?
```suggestion
  local code=$?
```

2021-12-24 11:36 UTC, akinomyoga commented on themes/pzq/pzq.theme.sh
> +  MAX_PWD_LENGTH=20
Do we want to expose the value to users? If not, we can make it local.

```suggestion
  local MAX_PWD_LENGTH=20
```

2021-12-24 11:36 UTC, akinomyoga commented on themes/pzq/pzq.theme.sh
> +  RELATIVE_PWD=${PWD/#$HOME/\~}
```suggestion
  local RELATIVE_PWD=${PWD/#$HOME/\~}
```

2021-12-24 11:36 UTC, akinomyoga commented on themes/pzq/pzq.theme.sh
> +      TRUNCATED_PWD=${RELATIVE_PWD:$offset:$MAX_PWD_LENGTH}
```suggestion
      local TRUNCATED_PWD=${RELATIVE_PWD:$offset:$MAX_PWD_LENGTH}
```

2021-12-24 11:36 UTC, akinomyoga commented on themes/pzq/pzq.theme.sh
> +    virtualenv=`basename "$VIRTUAL_ENV"`
```suggestion
    local virtualenv=$(basename "$VIRTUAL_ENV")
```

Prefer `$(...)` to ``` `...` ``` which is deprecated by POSIX.

2021-12-24 11:36 UTC, akinomyoga commented on themes/pzq/pzq.theme.sh
> +    VIRTUALENV_THEME_PROMPT_SUFFIX=')'
```suggestion
    local VIRTUALENV_THEME_PROMPT_PREFIX='('
    local VIRTUALENV_THEME_PROMPT_SUFFIX=')'
```

2021-12-24 11:36 UTC, akinomyoga commented on themes/pzq/pzq.theme.sh
> +  if [ $(uname) = "Linux" ];
```suggestion
  if [ "$OSTYPE" = "linux-gnu" ];
```

2021-12-24 11:36 UTC, akinomyoga commented on themes/pzq/pzq.theme.sh
> +    CONDAENV_THEME_PROMPT_SUFFIX=')'
```suggestion
    local CONDAENV_THEME_PROMPT_PREFIX='('
    local CONDAENV_THEME_PROMPT_SUFFIX=')'
```

2021-12-24 11:36 UTC, akinomyoga commented on themes/pzq/pzq.theme.sh
> +  local RESTORE_CURSOR='\033[u'
Modern terminals may not support these SCO sequences. Most terminals support `\e7` and `\e8`, respectively. Also, by using `\[...\]`, we need to let Bash know that the cursor movements between these two values are canceled.

```suggestion
  local SAVE_CURSOR='\[\e7'
  local RESTORE_CURSOR='\e8\]'
```

Or, if you want to make them work in a wider range of terminals, you could obtain them through `tput sc` and `tput rc`, respectively.

2021-12-24 11:36 UTC, akinomyoga commented on themes/pzq/pzq.theme.sh
> +  local MOVE_CURSOR_RIGHTMOST='\033[500C'
500 might not be sufficient for this 4K era...

```suggestion
  local MOVE_CURSOR_RIGHTMOST='\033['${COLUMNS:-9999}'C'
```

2021-12-24 11:36 UTC, akinomyoga commented on themes/pzq/pzq.theme.sh
> +      TITLEBAR="\033]0;\w\007"
```suggestion
      TITLEBAR="\[\033]0;\w\e\\\]"
```

- OSC terminated by BEL is deprecated. It is recommended to use the ANSI form terminated by ST (`\e\\`).
- We need to enclose it with `\[...\]` to let Bash know that the cursor will not be moved by the sequence.

2021-12-24 11:38 UTC, akinomyoga commented
Please also add an image of the theme and update [themes/THEMES.md](https://github.com/ohmybash/oh-my-bash/blob/master/themes/THEMES.md)!

2022-07-04 21:38 UTC, akinomyoga commented
I'm thinking of taking over this PR. If you still would like to work on it by yourself, please let me know.

2022-08-30 03:13 UTC, akinomyoga approved these changes

2022-08-30 03:34 UTC, akinomyoga commented
I have rebased the PR on top of the latest master, applied suggested changes, and added other fixes. I have also added an image of the theme in `themes/THEMES.md`. I'll keep this PR for about one week and am going to merge it if there is no further comments. @nntoan If you would like to review the PR, please let me know, in which case I'll wait for your review before merging.

2022-08-30 04:36 UTC, ZQPei commented
LGTM

2022-08-30 04:39 UTC, akinomyoga commented
@ZQPei Thank you for checking the changes to the PR!

2022-09-07 21:17 UTC, merged