Add half-life theme inspired from oh-my-zsh
ohmybash/oh-my-bash pull request #255
Opened 2021-11-10 21:51 UTC by memduhcagridemir

This PR adds a new theme similar to half-life theme of oh-my-zsh.

Here is a screenshot of how it looks;
![half-life theme](https://user-images.githubusercontent.com/4460628/141199236-4b97ef64-5e09-41f6-aacc-1d6f1d59581d.png)

2021-12-08 20:45 UTC, memduhcagridemir commented
@nntoan @chaifeng could you take a look?

2021-12-24 11:11 UTC, akinomyoga requested changes

2021-12-24 11:11 UTC, akinomyoga commented on themes/half-life/half-life.theme.sh
> +function prompt_command() {
It is better to make these two functions consistent.

```suggestion
prompt_command() {
```

2021-12-24 11:11 UTC, akinomyoga commented on themes/half-life/half-life.theme.sh
> +  CHAR=$(scm_char)
```suggestion
  local CHAR=$(scm_char)
```

2021-12-24 11:11 UTC, akinomyoga commented on themes/half-life/half-life.theme.sh
> +  ps_user_mark="${orange}λ${normal}"
```suggestion
  local ps_username="${purple}\u${normal}"
  local ps_path="${green}\w${normal}"
  local ps_user_mark="${orange}λ${normal}"
```

2021-12-24 11:11 UTC, akinomyoga commented on themes/half-life/half-life.theme.sh
> +  if [ $CHAR = $SCM_NONE_CHAR ]
```suggestion
  if [ "$CHAR" = "$SCM_NONE_CHAR" ]
```

2021-12-30 13:01 UTC, closed without merging

2021-12-30 13:28 UTC, akinomyoga commented
Ah, sorry. As you have been working on the `master` branch for this PR, I have failed to correctly push the rebased commits. The PR has been unintendedly closed, and I cannot reopen the PR again...

I'm sorry, but could you again force-push your changes to the `master` branch of `memduhcagridemir/oh-my-bash`? Or, can you force-push the commit of the [`pull255`](https://github.com/ohmybash/oh-my-bash/tree/pull255) branch of `ohmybash/oh-my-bash` to the `master` branch of `memduhcagridemir/oh-my-bash`?

<details><summary><b>In case you don't know how to do it, let me explain it here.</b></summary>

**Step 1**: If you don't have a local repository, you first need to clone the GitHub repository to a local repository:

```bash
$ git clone git@github.com:memduhcagridemir/oh-my-bash.git
$ cd oh-my-bash
$ git remote add upstream git@github.com:akinomyoga/oh-my-bash.git
```

**Step 2**: Check the names of remote repositories inside the local repository

```bash
$ git remote -v
origin        git@github.com:memduhcagridemir/oh-my-bash (fetch)
origin        git@github.com:memduhcagridemir/oh-my-bash (push)
upstream        git@github.com:ohmybash/oh-my-bash (fetch)
upstream        git@github.com:ohmybash/oh-my-bash (push)
```

In this case, your GitHub repository is `origin` and the source repository is `upstream`. If you haven't registered the source repository, you need add it by

```bash
$ git remote add upstream git@github.com:akinomyoga/oh-my-bash.git
```

**Step 3**: If you have any unsaved changes in the working tree or in the index, please save them (by making commits or by `git stash`).

**Step 4**: Please replace `upstream` in the following command with the name that we have checked in step 2.

```bash
$ git checkout master
$ git branch master-backup
$ git fetch upstream
$ git reset --hard upstream/master
$ git push -f origin master
```

</details>