oh-my-bash/plugins:add readme.md
ohmybash/oh-my-bash pull request #554
Opened 2024-04-19 00:36 UTC by JoseMRT2004

I added a readme that has a small overview of what each of the plugins does and included information on how to install them.👀

2024-04-25 02:40 UTC, akinomyoga commented on plugins/README.md
> +### Oh My Bash: Enhancing Your Development Experience
I'm wondering about the heading level. Why doesn't this start with the `<h1>` level (i.e. single `#`)? Could you make it `<h1>`?

2024-04-25 02:40 UTC, akinomyoga commented on plugins/README.md
> +_**Embracing a suite of plugins can significantly boost your coding efficiency by automating repetitive tasks, thereby making them less monotonous and easier to execute.**_
Boldfacing the entire sentence seems too strong. I'd prefer just italicization.

2024-04-25 02:40 UTC, akinomyoga commented on plugins/README.md
> +[ "$SSH_TTY" ] && plugins+=(tmux-autoattach)
```suggestion
[[ $SSH_TTY ]] && plugins+=(tmux-autoattach)
```

We want to gradually normalize the styles to use Bash constructs.

2024-04-25 04:06 UTC, JoseMRT2004 commented
**all ready ✅**

2024-04-25 05:01 UTC, akinomyoga requested changes
Thanks for updating. See below.

2024-04-25 05:01 UTC, akinomyoga commented on plugins/README.md
> +[ [ $SSH_TTY ] ] && plugins+=(tmux-autoattach)
```suggestion
[[ $SSH_TTY ]] && plugins+=(tmux-autoattach)
```

It's not `[ [ ... ] ]`. It's `[[ ... ]]`.

2024-04-25 05:31 UTC, akinomyoga commented on plugins/README.md
> +[ [ $SSH_TTY ] ] && plugins+=(tmux-autoattach)
Thanks.

2024-04-25 05:46 UTC, akinomyoga submitted a review, later dismissed
LGTM for now.

2024-04-25 06:44 UTC, JoseMRT2004 commented
**Entonces a darle**. _It's something like that in English So let's do it_

2024-04-27 19:57 UTC, akinomyoga reviewed
I've again checked this.

Could you update the title of the document?

I also added commit c25b10b9be714d9660b54bf8edac0185875dc8cf. We now have a list of the plugins, so we need to notify the authors of new plugins to update the list to keep it up-to-date.

2024-04-27 19:57 UTC, akinomyoga commented on plugins/README.md
> +# Oh My Bash: Enhancing Your Development Experience
This README is the one for OMB plugins, so "Oh My Bash" doesn't seem the correct title. For example,

```suggestion
# Oh-My-Bash Plugins: Enhancing Your Development Experience
```

2024-04-27 19:59 UTC, akinomyoga commented
Note: I force-pushed the branch on top of the latest master. You'll need to reset or merge the remote branch.

2024-04-28 03:36 UTC, akinomyoga approved these changes

2024-04-28 03:37 UTC, merged

2024-04-28 03:37 UTC, akinomyoga commented
Thanks!